version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/android:2023.02
    steps:
      - checkout
      - run:
          name: "Assemnle"
          command: ./gradlew :app:assembleDebug --info

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
